In [2]:
import pandas as pd
from pathlib import Path
from time import sleep
from ideam_dhime import download_dhime_data

In [2]:
# Lectura archivo de consulta de estaciones
ruta_estaciones = "../../data/raw/E_precipitacion.csv"
df_estaciones = pd.read_csv(ruta_estaciones)
df_estaciones.head()

,codigo,nombre,categoria,estado,municipio,altitud,longitud,latitud,fecha_instalacion,fecha_suspension
0,35190010,CINTAS LAS [35190010],Pluviográfica,Activa,Sogamoso,3400,-72.867667,5.614139,1971-02-15,NaN
1,23110040,TRIQUE EL [23110040],Pluviométrica,Activa,Puerto Boyacá,179,-74.568342,5.880889,1974-08-15,NaN
2,23125010,MUZO [23125010],Climatológica Ordinaria,Suspendida,Muzo,824,-74.133333,5.533333,1936-01-15,NaN
3,24030100,TERMOPAIPA [24030100],Pluviométrica,Suspendida,Paipa,2580,-73.150000,5.766667,1955-11-15,NaN
4,23120110,BRICENO [23120110],Pluviométrica,Suspendida,Briceño,1500,-73.950000,5.700000,1960-05-15,NaN

In [3]:
# Directorio de salida para datos descargados
download_path = Path("../../data/raw/dhime/precipitacion")
download_path.mkdir(parents=True, exist_ok=True)

In [4]:
# Parámetros generales
departamento = "Boyacá"
parameter = "Precipitación"
variable_code = "Precipitación total mensual"

date_ini = "01/01/1950"
date_fin = "01/05/2026"

resultados = []

In [5]:
for idx, estacion in df_estaciones.iterrows():

    codigo_estacion = str(estacion["codigo"])
    municipio = str(estacion["municipio"])
    nombre = str(estacion["nombre"])

    print(f"\nConsultando {idx} | {codigo_estacion} | {nombre} | {municipio}")

    try:
        csv_final = download_dhime_data(
            download_path=str(download_path),
            station_code=codigo_estacion,
            department=departamento,
            municipality=municipio,
            parameter=parameter,
            variable_code=variable_code,
            date_ini=date_ini,
            date_fin=date_fin,
            time_wait=180
        )

        resultados.append({
            "codigo": codigo_estacion,
            "nombre": nombre,
            "municipio": municipio,
            "estado_descarga": "ok",
            "archivo": str(csv_final),
            "error": None
        })

        print(f"Descarga OK: {csv_final}")

    except Exception as e:

        resultados.append({
            "codigo": codigo_estacion,
            "nombre": nombre,
            "municipio": municipio,
            "estado_descarga": "error",
            "archivo": None,
            "error": str(e)
        })

        print(f"Error en {codigo_estacion}: {e}")

#    sleep(5)

df_resultados = pd.DataFrame(resultados)

df_resultados.to_csv(
    "../../data/raw/dhime/logs/precipitacion_log_descargas.csv",
    index=False,
    encoding="utf-8-sig"
)

df_resultados

Consultando 0 | 35190010 | CINTAS LAS [35190010] | Sogamoso
Descarga OK: ../../data/raw/dhime/precipitacion/35190010-Precipitación_total_mensual-01011950-01052026-final.csv

Consultando 1 | 23110040 | TRIQUE EL [23110040] | Puerto Boyacá
Descarga OK: ../../data/raw/dhime/precipitacion/23110040-Precipitación_total_mensual-01011950-01052026-final.csv

Consultando 2 | 23125010 | MUZO  [23125010] | Muzo
Error en 23125010: No se encontró la estación 23125010 en la lista de Muzo.

Consultando 3 | 24030100 | TERMOPAIPA  [24030100] | Paipa
Descarga OK: ../../data/raw/dhime/precipitacion/24030100-Precipitación_total_mensual-01011950-01052026-final.csv

Consultando 4 | 23120110 | BRICENO  [23120110] | Briceño
Error en 23120110: Fallo definitivo al hacer clic en Seleccionar municipio (Briceño).

Consultando 5 | 24015060 | FABRICA TEXTIL  [24015060] | Samacá
Error en 24015060: No se encontró la estación 24015060 en la lista de Samacá.

Consultando 6 | 24035070 | GUICAN [24035070] | Guicán
Descarga OK: ../../data/raw/dhime/precipitacion/24035070-Precipitación_total_mensual-01011950-01052026-final.csv

Consultando 7 | 24030460 | GUACHATA  [24030460] | Tota
Descarga OK: ../../data/raw/dhime/precipitacion/24030460-Precipitación_total_mensual-01011950-01052026-final.csv

Consultando 8 | 2403500363 | ESTACIÓN VEREDA AGUA BLANCA - AUT [2403500363] | Tuta
Error en 2403500363: No se encontró la estación 2403500363 en la lista de Tuta.

Consultando 9 | 24010120 | REPRESA  [24010120] | Samacá
Descarga OK: ../../data/raw/dhime/precipitacion/24010120-Precipitación_total_mensual-01011950-01052026-final.csv

Consultando 10 | 24011050 | MUSEO EL [24011050] | Villa De Leiva
Error en 24011050: No se encontró la estación 24011050 en la lista de Villa De Leiva.

Consultando 11 | 24010830 | SAN PEDRO IGUAQUE [24010830] | Chíquiza
Descarga OK: ../../data/raw/dhime/precipitacion/24010830-Precipitación_total_mensual-01011950-01052026-final.csv

Consultando 12 | 24030820 | LOS AZULEJOS [24030820] | Tuta
Descarga OK: ../../data/raw/dhime/precipitacion/24030820-Precipitación_total_mensual-01011950-01052026-final.csv

Consultando 13 | 24030380 | SOTAQUIRA [24030380] | Sotaquirá
Descarga OK: ../../data/raw/dhime/precipitacion/24030380-Precipitación_total_mensual-01011950-01052026-final.csv

Consultando 14 | 24030800 | CASA AMARILLA [24030800] | Toca
Descarga OK: ../../data/raw/dhime/precipitacion/24030800-Precipitación_total_mensual-01011950-01052026-final.csv

Consultando 15 | 24010800 | MINAS LAS [24010800] | Samacá
Descarga OK: ../../data/raw/dhime/precipitacion/24010800-Precipitación_total_mensual-01011950-01052026-final.csv

Consultando 16 | 35070120 | MACANAL [35070120] | Macanal
Descarga OK: ../../data/raw/dhime/precipitacion/35070120-Precipitación_total_mensual-01011950-01052026-final.csv

Consultando 17 | 35190110 | CUSIANA-TOQUILLA  [35190110] | Aquitania
Error en 35190110: No se encontró la estación 35190110 en la lista de Aquitania.

Consultando 18 | 23120250 | BORBUR 2 [23120250] | San Pablo De Borbur
Descarga OK: ../../data/raw/dhime/precipitacion/23120250-Precipitación_total_mensual-01011950-01052026-final.csv

Consultando 19 | 24030900 | COL ORTIZ  [24030900] | Tunja
Descarga OK: ../../data/raw/dhime/precipitacion/24030900-Precipitación_total_mensual-01011950-01052026-final.csv

Consultando 20 | 35190050 | PAJARITO [35190050] | Pajarito
Descarga OK: ../../data/raw/dhime/precipitacion/35190050-Precipitación_total_mensual-01011950-01052026-final.csv

Consultando 21 | 24030530 | SAN ANTONIO [24030530] | Tuta
Descarga OK: ../../data/raw/dhime/precipitacion/24030530-Precipitación_total_mensual-01011950-01052026-final.csv

Consultando 22 | 24031030 | IZA [24031030] | Iza
Error en 24031030: SIN_SOLAPE: estación 24031030 solicitado=01/01/1950->01/05/2026 real=01/07/1928->01/09/1928

Consultando 23 | 23120150 | MARIPI [23120150] | Maripí
Descarga OK: ../../data/raw/dhime/precipitacion/23120150-Precipitación_total_mensual-01011950-01052026-final.csv

Consultando 24 | 35165000 | EL TUNEL [35165000] | Cuítiva
Error en 35165000: No se encontró la estación 35165000 en la lista de Cuítiva.

Consultando 25 | 24011120 | JASSA LA [24011120] | Samacá
Descarga OK: ../../data/raw/dhime/precipitacion/24011120-Precipitación_total_mensual-01011950-01052026-final.csv

Consultando 26 | 24011040 | SABOYA  [24011040] | Saboyá
Error en 24011040: SIN_SOLAPE: estación 24011040 solicitado=01/01/1950->01/05/2026 real=01/01/1946->01/12/1946

Consultando 27 | 35070430 | GARAGOA  [35070430] | Garagoa
Descarga OK: ../../data/raw/dhime/precipitacion/35070430-Precipitación_total_mensual-01011950-01052026-final.csv

Consultando 28 | 24030780 | HOTEL EL [24030780] | Toca
Descarga OK: ../../data/raw/dhime/precipitacion/24030780-Precipitación_total_mensual-01011950-01052026-final.csv

Consultando 29 | 24030510 | CEREZO EL [24030510] | Paipa
Descarga OK: ../../data/raw/dhime/precipitacion/24030510-Precipitación_total_mensual-01011950-01052026-final.csv

Consultando 30 | 35085010 | MIRAFLORES [35085010] | Miraflores
Error en 35085010: Fallo definitivo al hacer clic en Seleccionar municipio (Miraflores).

Consultando 31 | 24035420 | CERINZA [240354200] | Cerinza
Descarga OK: ../../data/raw/dhime/precipitacion/24035420-Precipitación_total_mensual-01011950-01052026-final.csv

Consultando 32 | 35090020 | PUEBLO VIEJO  [35090020] | Aquitania
Descarga OK: ../../data/raw/dhime/precipitacion/35090020-Precipitación_total_mensual-01011950-01052026-final.csv

Consultando 33 | 35070060 | QUINCHOS LOS [35070060] | Chinavita
Descarga OK: ../../data/raw/dhime/precipitacion/35070060-Precipitación_total_mensual-01011950-01052026-final.csv

Consultando 34 | 2403000114 | LAS MERCEDES - AUT [2403000114] | Chiscas
Error en 2403000114: No se encontró la estación 2403000114 en la lista de Chiscas.

Consultando 35 | 35070100 | SOMONDOCO [35070100] | Somondoco
Descarga OK: ../../data/raw/dhime/precipitacion/35070100-Precipitación_total_mensual-01011950-01052026-final.csv

Consultando 36 | 2403500368 | ESTACIÓN COMPUERTA LAGO SOCHAGOTA - AUT [2403500368] | Paipa
Error en 2403500368: No se encontró la estación 2403500368 en la lista de Paipa.

Consultando 37 | 24030260 | COCUY EL [24030260] | El Cocuy
Descarga OK: ../../data/raw/dhime/precipitacion/24030260-Precipitación_total_mensual-01011950-01052026-final.csv

Consultando 38 | 24030840 | LA RUSIA ANTENA TV [24030840] | Duitama
Descarga OK: ../../data/raw/dhime/precipitacion/24030840-Precipitación_total_mensual-01011950-01052026-final.csv

Consultando 39 | 24010600 | CHIQUINQUIRA  [24010600] | Chiquinquirá
Descarga OK: ../../data/raw/dhime/precipitacion/24010600-Precipitación_total_mensual-01011950-01052026-final.csv

Consultando 40 | 35070460 | VOLADOR EL [35070460] | Macanal
Descarga OK: ../../data/raw/dhime/precipitacion/35070460-Precipitación_total_mensual-01011950-01052026-final.csv

Consultando 41 | 24035060 | COL PRESENTACION  [24035060] | Duitama
Error en 24035060: SIN_SOLAPE: estación 24035060 solicitado=01/01/1950->01/05/2026 real=01/06/1931->01/08/1937

Consultando 42 | 24030870 | PINOS LOS [24030870] | Duitama
Descarga OK: ../../data/raw/dhime/precipitacion/24030870-Precipitación_total_mensual-01011950-01052026-final.csv

Consultando 43 | 24035504 | COVARACHIA-24035504  - AUT  [24035504] | Covarachía
Error en 24035504: No se encontró la estación 24035504 en la lista de Covarachía.

Consultando 44 | 35080110 | ALTO MUCENO [35080110] | Macanal
Descarga OK: ../../data/raw/dhime/precipitacion/35080110-Precipitación_total_mensual-01011950-01052026-final.csv

Consultando 45 | 24030400 | SANTA ROSA D VITERBO [24030400] | Santa Rosa De Viterbo
Descarga OK: ../../data/raw/dhime/precipitacion/24030400-Precipitación_total_mensual-01011950-01052026-final.csv

Consultando 46 | 24015020 | BERTHA  [24015020] | Moniquirá
Descarga OK: ../../data/raw/dhime/precipitacion/24015020-Precipitación_total_mensual-01011950-01052026-final.csv

Consultando 47 | 24010730 | CUEVA LA HACIENDA [24010730] | Motavita
Error en 24010730: No se encontró la estación 24010730 en la lista de Motavita.

Consultando 48 | 35190100 | CUSIANA VADO HONDO  [35190100] | Pajarito
Error en 35190100: SIN_SOLAPE: estación 35190100 solicitado=01/01/1950->01/05/2026 real=01/08/1947->01/08/1948

Consultando 49 | 24030660 | MORTINO EL [24030660] | El Cocuy
Descarga OK: ../../data/raw/dhime/precipitacion/24030660-Precipitación_total_mensual-01011950-01052026-final.csv

Consultando 50 | 35095010 | AQUITANIA [35095010] | Aquitania
Descarga OK: ../../data/raw/dhime/precipitacion/35095010-Precipitación_total_mensual-01011950-01052026-final.csv

Consultando 51 | 2403500367 | ESTACIÓN ENTRADA LAGO SOCHAGOTA - AUT [2403500367] | Paipa
Error en 2403500367: No se encontró la estación 2403500367 en la lista de Paipa.

Consultando 52 | 24035290 | CHUSCAL EL  [24035290] | Monguí
Descarga OK: ../../data/raw/dhime/precipitacion/24035290-Precipitación_total_mensual-01011950-01052026-final.csv

Consultando 53 | 23120080 | BORBUR 1 [23120080] | San Pablo De Borbur
Descarga OK: ../../data/raw/dhime/precipitacion/23120080-Precipitación_total_mensual-01011950-01052026-final.csv

Consultando 54 | 35085050 | CAMPOHERMOSO [35085050] | Campohermoso
Descarga OK: ../../data/raw/dhime/precipitacion/35085050-Precipitación_total_mensual-01011950-01052026-final.csv

Consultando 55 | 24010710 | MONIQUIRA [24010710] | Moniquirá
Descarga OK: ../../data/raw/dhime/precipitacion/24010710-Precipitación_total_mensual-01011950-01052026-final.csv

Consultando 56 | 24015310 | SAN MIGUEL DE SEMA  [24015310] | San Miguel De Sema
Descarga OK: ../../data/raw/dhime/precipitacion/24015310-Precipitación_total_mensual-01011950-01052026-final.csv

Consultando 57 | 24030250 | CHITA  [24030250] | Chita
Descarga OK: ../../data/raw/dhime/precipitacion/24030250-Precipitación_total_mensual-01011950-01052026-final.csv

Consultando 58 | 24035080 | PAIPA I A  [24035080] | Paipa
Error en 24035080: No se encontró la estación 24035080 en la lista de Paipa.

Consultando 59 | 24030350 | DUITAMA [24030350] | Duitama
Descarga OK: ../../data/raw/dhime/precipitacion/24030350-Precipitación_total_mensual-01011950-01052026-final.csv

Consultando 60 | 24035508 | SAN ANTONIO-24035508  - AUT  [24035508] | Tuta
Error en 24035508: No se encontró la estación 24035508 en la lista de Tuta.

Consultando 61 | 24030940 | SENA [24030940] | Sogamoso
Descarga OK: ../../data/raw/dhime/precipitacion/24030940-Precipitación_total_mensual-01011950-01052026-final.csv

Consultando 62 | 35070320 | MARTOTA [35070320] | Somondoco
Descarga OK: ../../data/raw/dhime/precipitacion/35070320-Precipitación_total_mensual-01011950-01052026-final.csv

Consultando 63 | 35160000 | LAS CINTAS [35160000] | Sogamoso
Error en 35160000: No se encontró la estación 35160000 en la lista de Sogamoso.

Consultando 64 | 35070190 | CHIVOR [35070190] | Chivor
Descarga OK: ../../data/raw/dhime/precipitacion/35070190-Precipitación_total_mensual-01011950-01052026-final.csv

Consultando 65 | 24030430 | BELENCITO  [24030430] | Nobsa
Descarga OK: ../../data/raw/dhime/precipitacion/24030430-Precipitación_total_mensual-01011950-01052026-final.csv

Consultando 66 | 23120280 | BUENAVISTA  [23120280] | Buenavista
Error en 23120280: Fallo definitivo al hacer clic en Seleccionar municipio (Buenavista).

Consultando 67 | 24015360 | SABOYA LA GRANJA [24015360] | Saboyá
Descarga OK: ../../data/raw/dhime/precipitacion/24015360-Precipitación_total_mensual-01011950-01052026-final.csv

Consultando 68 | 35080030 | CAMP BUENAVISTA [35080030] | Berbeo
Descarga OK: ../../data/raw/dhime/precipitacion/35080030-Precipitación_total_mensual-01011950-01052026-final.csv

Consultando 69 | 35080010 | ZETAQUIRA [35080010] | Zetaquirá
Descarga OK: ../../data/raw/dhime/precipitacion/35080010-Precipitación_total_mensual-01011950-01052026-final.csv

Consultando 70 | 24011000 | GACHANECA  [24011000] | Samacá
Descarga OK: ../../data/raw/dhime/precipitacion/24011000-Precipitación_total_mensual-01011950-01052026-final.csv

Consultando 71 | 35070290 | TENZA [35070290] | Tenza
Error en 35070290: SIN_SOLAPE: estación 35070290 solicitado=01/01/1950->01/05/2026 real=01/08/1929->01/05/1941

Consultando 72 | 24031010 | COCUY EL [24031010] | El Cocuy
Error en 24031010: SIN_SOLAPE: estación 24031010 solicitado=01/01/1950->01/05/2026 real=01/01/1934->01/05/1942

Consultando 73 | 24035230 | JESUITAS  [24035230] | Santa Rosa De Viterbo
Descarga OK: ../../data/raw/dhime/precipitacion/24035230-Precipitación_total_mensual-01011950-01052026-final.csv

Consultando 74 | 24035190 | SAN JOSE  [24035190] | Siachoque
Descarga OK: ../../data/raw/dhime/precipitacion/24035190-Precipitación_total_mensual-01011950-01052026-final.csv

Consultando 75 | 35085040 | VIVERO EL [35085040] | Miraflores
Error en 35085040: Fallo definitivo al hacer clic en Seleccionar municipio (Miraflores).

Consultando 76 | 24035180 | SAN RAFAEL [24035180] | Nobsa
Descarga OK: ../../data/raw/dhime/precipitacion/24035180-Precipitación_total_mensual-01011950-01052026-final.csv

Consultando 77 | 35080060 | CEDROS LOS [35080060] | Campohermoso
Descarga OK: ../../data/raw/dhime/precipitacion/35080060-Precipitación_total_mensual-01011950-01052026-final.csv

Consultando 78 | 2403500362 | ESTACIÓN PLAYA ABAJO - AUT [2403500362] | Tuta
Error en 2403500362: No se encontró la estación 2403500362 en la lista de Tuta.

Consultando 79 | 23120210 | COPER [23120210] | Coper
Descarga OK: ../../data/raw/dhime/precipitacion/23120210-Precipitación_total_mensual-01011950-01052026-final.csv

Consultando 80 | 24035250 | CHITA  - AUT [24035250] | Chita
Descarga OK: ../../data/raw/dhime/precipitacion/24035250-Precipitación_total_mensual-01011950-01052026-final.csv

Consultando 81 | 35090060 | CAZADERO [35090060] | Aquitania
Descarga OK: ../../data/raw/dhime/precipitacion/35090060-Precipitación_total_mensual-01011950-01052026-final.csv

Consultando 82 | 24035030 | SOGAMOSO  [24035030] | Sogamoso
Descarga OK: ../../data/raw/dhime/precipitacion/24035030-Precipitación_total_mensual-01011950-01052026-final.csv

Consultando 83 | 2403500361 | ESTACIÓN PTAR -AUT [2403500361] | Oicatá
Error en 2403500361: No se encontró la estación 2403500361 en la lista de Oicatá.

Consultando 84 | 35195060 | TOQUILLA - AUT [35195060] | Aquitania
Descarga OK: ../../data/raw/dhime/precipitacion/35195060-Precipitación_total_mensual-01011950-01052026-final.csv

Consultando 85 | 24030170 | SOCOTA [24030170] | Socotá
Descarga OK: ../../data/raw/dhime/precipitacion/24030170-Precipitación_total_mensual-01011950-01052026-final.csv

Consultando 86 | 24011130 | BRASILIA FINCA [24011130] | San Miguel De Sema
Error en 24011130: No se encontró la estación 24011130 en la lista de San Miguel De Sema.

Consultando 87 | 24010460 | STA SOFIA  [24010460] | Santa Sofía
Descarga OK: ../../data/raw/dhime/precipitacion/24010460-Precipitación_total_mensual-01011950-01052026-final.csv

Consultando 88 | 24030010 | SOATA  [24030010] | Soatá
Descarga OK: ../../data/raw/dhime/precipitacion/24030010-Precipitación_total_mensual-01011950-01052026-final.csv

Consultando 89 | 35090100 | EL ALISAL [35090100] | Aquitania
Descarga OK: ../../data/raw/dhime/precipitacion/35090100-Precipitación_total_mensual-01011950-01052026-final.csv

Consultando 90 | 24030700 | COVARACHIA [24030700] | Covarachía
Descarga OK: ../../data/raw/dhime/precipitacion/24030700-Precipitación_total_mensual-01011950-01052026-final.csv

Consultando 91 | 24030910 | SEMINARIO  [24030910] | Tunja
Error en 24030910: SIN_SOLAPE: estación 24030910 solicitado=01/01/1950->01/05/2026 real=01/01/1923->01/06/1944

Consultando 92 | 24010260 | CANDELARIA LA  [24010260] | Ráquira
Descarga OK: ../../data/raw/dhime/precipitacion/24010260-Precipitación_total_mensual-01011950-01052026-final.csv

Consultando 93 | 24030190 | MONGUI [24030190] | Monguí
Descarga OK: ../../data/raw/dhime/precipitacion/24030190-Precipitación_total_mensual-01011950-01052026-final.csv

Consultando 94 | 23120120 | STA RITA  [23120120] | Pauna
Descarga OK: ../../data/raw/dhime/precipitacion/23120120-Precipitación_total_mensual-01011950-01052026-final.csv

Consultando 95 | 2403500372 | ESTACIÓN EL MOLINO - AUT [2403500372] | Gámeza
Error en 2403500372: No se encontró la estación 2403500372 en la lista de Gámeza.

Consultando 96 | 24030610 | EMPODUITAMA [24030610] | Duitama
Descarga OK: ../../data/raw/dhime/precipitacion/24030610-Precipitación_total_mensual-01011950-01052026-final.csv

Consultando 97 | 35070040 | TIBANA [35070040] | Tibaná
Descarga OK: ../../data/raw/dhime/precipitacion/35070040-Precipitación_total_mensual-01011950-01052026-final.csv

Consultando 98 | 24030390 | PTE PINZON  [24030390] | Boavita
Descarga OK: ../../data/raw/dhime/precipitacion/24030390-Precipitación_total_mensual-01011950-01052026-final.csv

Consultando 99 | 3516500203 | ALISAL [3516500203] | Aquitania
Descarga OK: ../../data/raw/dhime/precipitacion/3516500203-Precipitación_total_mensual-01011950-01052026-final.csv

Consultando 100 | 35080100 | PUENTE FORERO [35080100] | Garagoa
Descarga OK: ../../data/raw/dhime/precipitacion/35080100-Precipitación_total_mensual-01011950-01052026-final.csv

Consultando 101 | 35070450 | SITIO PRESA [35070450] | Santa María
Error en 35070450: Fallo definitivo al hacer clic en Seleccionar municipio (Santa María).

Consultando 102 | 24030640 | NIMICIA ESCUELA RURAL [24030640] | Gámeza
Descarga OK: ../../data/raw/dhime/precipitacion/24030640-Precipitación_total_mensual-01011950-01052026-final.csv

Consultando 103 | 35070580 | RAMIRIQUI  - AUT  [35070580] | Ramiriquí
Error en 35070580: No se encontró la estación 35070580 en la lista de Ramiriquí.

Consultando 104 | 35095030 | TUNEL EL [35095030] | Cuítiva
Descarga OK: ../../data/raw/dhime/precipitacion/35095030-Precipitación_total_mensual-01011950-01052026-final.csv

Consultando 105 | 24010030 | COL JESUS MARIA JO  [24010030] | Chiquinquirá
Error en 24010030: No se encontró la estación 24010030 en la lista de Chiquinquirá.

Consultando 106 | 35070070 | CHINAVITA [35070070] | Chinavita
Descarga OK: ../../data/raw/dhime/precipitacion/35070070-Precipitación_total_mensual-01011950-01052026-final.csv

Consultando 107 | 23125080 | OTANCHE [23125080] | Otanche
Descarga OK: ../../data/raw/dhime/precipitacion/23125080-Precipitación_total_mensual-01011950-01052026-final.csv

Consultando 108 | 35090070 | GUAMO DE SISBACA [35090070] | Aquitania
Descarga OK: ../../data/raw/dhime/precipitacion/35090070-Precipitación_total_mensual-01011950-01052026-final.csv

Consultando 109 | 35070200 | CARACOL EL [35070200] | Garagoa
Descarga OK: ../../data/raw/dhime/precipitacion/35070200-Precipitación_total_mensual-01011950-01052026-final.csv

Consultando 110 | 24035160 | ESPERANZA LA  [24035160] | Sativanorte
Descarga OK: ../../data/raw/dhime/precipitacion/24035160-Precipitación_total_mensual-01011950-01052026-final.csv

Consultando 111 | 24030570 | APOSENTOS [24030570] | Socotá
Descarga OK: ../../data/raw/dhime/precipitacion/24030570-Precipitación_total_mensual-01011950-01052026-final.csv

Consultando 112 | 35070180 | SANTA MARIA [35070180] | Santa María
Error en 35070180: Fallo definitivo al hacer clic en Seleccionar municipio (Santa María).

Consultando 113 | 24030540 | FIRAVITOBA [24030540] | Firavitoba
Descarga OK: ../../data/raw/dhime/precipitacion/24030540-Precipitación_total_mensual-01011950-01052026-final.csv

Consultando 114 | 35070240 | SALITRE  [35070240] | Guateque
Descarga OK: ../../data/raw/dhime/precipitacion/35070240-Precipitación_total_mensual-01011950-01052026-final.csv

Consultando 115 | 24030410 | TIBASOSA [24030410] | Tibasosa
Descarga OK: ../../data/raw/dhime/precipitacion/24030410-Precipitación_total_mensual-01011950-01052026-final.csv

Consultando 116 | 24015010 | GACHANECA REPRESA  [24015010] | Samacá
Descarga OK: ../../data/raw/dhime/precipitacion/24015010-Precipitación_total_mensual-01011950-01052026-final.csv

Consultando 117 | 35085030 | PAEZ [35085030] | Páez

,codigo,nombre,municipio,estado_descarga,archivo,error
0,35190010,CINTAS LAS [35190010],Sogamoso,ok,../../data/raw/dhime/precipitacion/35190010-Pr...,None
1,23110040,TRIQUE EL [23110040],Puerto Boyacá,ok,../../data/raw/dhime/precipitacion/23110040-Pr...,None
2,23125010,MUZO [23125010],Muzo,error,None,No se encontró la estación 23125010 en la list...
3,24030100,TERMOPAIPA [24030100],Paipa,ok,../../data/raw/dhime/precipitacion/24030100-Pr...,None
4,23120110,BRICENO [23120110],Briceño,error,None,Fallo definitivo al hacer clic en Seleccionar ...
...,...,...,...,...,...,...
206,35070210,PACHAVITA [35070210],Pachavita,ok,../../data/raw/dhime/precipitacion/35070210-Pr...,None
207,23120130,STA BARBARA [23120130],San Pablo De Borbur,ok,../../data/raw/dhime/precipitacion/23120130-Pr...,None
208,24035040,LA COPA [24035040],Toca,ok,../../data/raw/dhime/precipitacion/24035040-Pr...,None
209,35070220,JENESANO [35070220],Jenesano,ok,../../data/raw/dhime/precipitacion/35070220-Pr...,None
210,24010630,ARCABUCO [24010630],Arcabuco,ok,../../data/raw/dhime/precipitacion/24010630-Pr...,None

In [ ]:
# Elimina archivos redundantes
ruta_datos = Path("../../data/raw/dhime/precipitacion")

eliminados = []

for archivo in ruta_datos.glob("*.csv"):

    nombre = archivo.name

    # conservar log
    if nombre == "precipitacion_log_descargas.csv":
        continue

    # conservar archivos finales
    if nombre.endswith("-final.csv"):
        continue

    archivo.unlink()

    eliminados.append(nombre)

print(f"Archivos eliminados: {len(eliminados)}")

Archivos eliminados: 295